# Generated by Django 6.0.2 on 2026-02-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='care_instructions',
        ),
    ]
