# Generated by Django 6.0.2 on 2026-02-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_plant_care_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
