# Generated by Django 6.0.2 on 2026-02-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_order_delivery_charge_order_delivery_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_bill',
        ),
    ]
