# Generated by Django 6.0.2 on 2026-03-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_orderitem_buying_price_plant_buying_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipFastRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('pickup_address', models.TextField()),
                ('estimated_parcels', models.IntegerField(blank=True, default=0, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('service_type', models.CharField(default='Regular', max_length=20)),
                ('rider', models.CharField(default='Unassigned', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shipfast_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
