# Generated by Django 6.0.2 on 2026-03-18 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_platformreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformReview',
        ),
    ]
