# Generated by Django 6.0.2 on 2026-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_exchangepost_is_available_exchangeproposalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepost',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
