# Generated by Django 6.0.2 on 2026-04-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_review_plant_review_seller_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='plant_name',
        ),
    ]
