# Generated by Django 6.0.2 on 2026-04-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_rename_name_plant_plant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='stock',
            new_name='stock_quantity',
        ),
    ]
