# Generated by Django 6.0.2 on 2026-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_rename_stock_plant_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='watering_frequency',
            field=models.IntegerField(default=7, help_text='Watering frequency in days'),
        ),
    ]
