# Generated by Django 6.0.2 on 2026-04-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_plant_watering_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='watering_frequency',
        ),
    ]
