# Generated by Django 6.0.4 on 2026-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Local IP of the Arduino/ESP32 device', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_scheduled_check',
            field=models.DateField(blank=True, help_text='Last date a scheduled check was performed', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='moisture_threshold',
            field=models.IntegerField(default=30, help_text='Alert when moisture% falls below this value'),
        ),
        migrations.AddField(
            model_name='device',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='plant_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='device',
            name='schedule_time',
            field=models.TimeField(blank=True, help_text='Daily time to check sensor readings', null=True),
        ),
    ]
