# Generated by Django 6.0.4 on 2026-05-06 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_device_ip_address_device_last_scheduled_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auto_watering_enabled',
            field=models.BooleanField(default=False, help_text='Allow system to water automatically'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_auto_water_date',
            field=models.DateField(blank=True, help_text='Last date auto-watering actually triggered', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat or successful communication', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_watered_at',
            field=models.DateTimeField(blank=True, help_text='Last time pump was run (manual or auto)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='pump_duration_seconds',
            field=models.IntegerField(default=5, help_text='Seconds to run pump per watering event', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='pump_status',
            field=models.BooleanField(default=False, help_text='True if pump was ON during reading'),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='soil_raw',
            field=models.IntegerField(default=0, help_text='Raw analog value from sensor'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_scheduled_check',
            field=models.DateField(blank=True, help_text='Last date a scheduled check was successfully performed', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='moisture_threshold',
            field=models.IntegerField(default=30, help_text='Alert when moisture% falls below this value', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='soil_moisture',
            field=models.FloatField(help_text='Calculated percentage'),
        ),
        migrations.CreateModel(
            name='WateringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Scheduled Auto'), ('manual', 'Manual User Trigger')], max_length=20)),
                ('moisture_before', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('response', models.CharField(blank=True, help_text='Response from device or error message', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_logs', to='iot.device')),
            ],
        ),
    ]
