# Generated by Django 6.0.6 on 2026-07-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_device_auto_watering_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='care_guide',
            field=models.TextField(blank=True, default='', help_text='AI-generated care guide for this plant'),
        ),
        migrations.AddField(
            model_name='device',
            name='plant_image',
            field=models.ImageField(blank=True, help_text='Photo of the plant on this pot', null=True, upload_to='device_plants/'),
        ),
    ]
