# Generated by Django 6.0.6 on 2026-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_device_care_guide_device_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereading',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='water_level',
            field=models.FloatField(default=0),
        ),
    ]
