# Generated by Django 6.0.2 on 2026-02-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_bio_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_captured',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to='nids/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nid_front',
            field=models.ImageField(blank=True, null=True, upload_to='nids/'),
        ),
    ]
