# Generated by Django 6.0.2 on 2026-04-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_latitude_customuser_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotanistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('nid_copy', models.ImageField(blank=True, null=True, upload_to='documents/nids/')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='documents/certificates/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
