# Generated by Django 6.0.2 on 2026-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_botanistapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botanistapplication',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='botanist_docs/'),
        ),
        migrations.AlterField(
            model_name='botanistapplication',
            name='nid_copy',
            field=models.ImageField(blank=True, null=True, upload_to='botanist_docs/'),
        ),
    ]
