# Generated by Django 6.0.2 on 2026-02-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='URL for category cover image', null=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Categories',
            },
        ),
        migrations.CreateModel(
            name='PlantVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('care_instructions', models.TextField(help_text='Detailed care instructions (Light, Water, Soil, etc.)')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='plant_care.plantcategory')),
            ],
            options={
                'verbose_name_plural': 'Plant Varieties',
            },
        ),
    ]
