# Generated by Django 6.0.2 on 2026-02-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantvariety',
            name='care_instructions',
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='care_type',
            field=models.CharField(choices=[('general', 'General Care (Applies to all varieties)'), ('specific', 'Variety Specific (Care differs by variety)')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='light_care',
            field=models.TextField(blank=True, help_text='General light requirements'),
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='plant_type',
            field=models.CharField(blank=True, help_text='e.g. Vining, Succulent, Herbaceous', max_length=100),
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for URL routing', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='soil_care',
            field=models.TextField(blank=True, help_text='General soil preferences'),
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='toxicity_care',
            field=models.TextField(blank=True, help_text='General toxicity information'),
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='water_care',
            field=models.TextField(blank=True, help_text='General watering instructions'),
        ),
        migrations.AddField(
            model_name='plantvariety',
            name='light_care',
            field=models.TextField(blank=True, help_text='Specific light requirements'),
        ),
        migrations.AddField(
            model_name='plantvariety',
            name='slug',
            field=models.SlugField(default='exit', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantvariety',
            name='soil_care',
            field=models.TextField(blank=True, help_text='Specific soil preferences'),
        ),
        migrations.AddField(
            model_name='plantvariety',
            name='toxicity_care',
            field=models.TextField(blank=True, help_text='Specific toxicity information'),
        ),
        migrations.AddField(
            model_name='plantvariety',
            name='variety_group',
            field=models.CharField(blank=True, help_text='e.g. Standard, Designer, Unique', max_length=50),
        ),
        migrations.AddField(
            model_name='plantvariety',
            name='water_care',
            field=models.TextField(blank=True, help_text='Specific watering instructions'),
        ),
    ]
