# Generated by Django 6.0.2 on 2026-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0003_notification_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.TextField(),
        ),
    ]
