# Generated by Django 6.0.2 on 2026-03-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0005_subscription_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='deliveries_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
