# Generated by Django 6.0.2 on 2026-03-19 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0006_subscription_deliveries_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g. Pothos, Succulent, Cactus', max_length=100, unique=True)),
                ('watering_interval_days', models.IntegerField(default=7)),
                ('fertilizer_interval_days', models.IntegerField(default=30)),
                ('repotting_interval_months', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicCareCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('last_watered_date', models.DateField(auto_now_add=True)),
                ('last_fertilized_date', models.DateField(auto_now_add=True)),
                ('last_repotting_date', models.DateField(auto_now_add=True)),
                ('source_order_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
