# Generated by Django 6.0.2 on 2026-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0009_remove_post_likes_count_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretemplate',
            name='fertilizer_type',
            field=models.CharField(default='Organic Fertilizer', help_text='e.g. NPK, Organic, Liquid Fertilizer', max_length=100),
        ),
    ]
