# Generated by Django 6.0.2 on 2026-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0010_caretemplate_fertilizer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccarecard',
            name='watering_frequency',
            field=models.IntegerField(default=7),
        ),
    ]
