# Generated by Django 6.0.2 on 2026-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0011_dynamiccarecard_watering_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccarecard',
            name='last_fertilized_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dynamiccarecard',
            name='last_repotting_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dynamiccarecard',
            name='last_watered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
