# Generated by Django 6.0.2 on 2026-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0012_alter_dynamiccarecard_last_fertilized_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamiccarecard',
            name='watering_frequency',
        ),
        migrations.AlterField(
            model_name='dynamiccarecard',
            name='last_fertilized_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dynamiccarecard',
            name='last_repotting_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dynamiccarecard',
            name='last_watered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
