# Generated by Django 6.0.2 on 2026-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0013_remove_dynamiccarecard_watering_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccarecard',
            name='fertilizer_frequency',
            field=models.IntegerField(default=30, help_text='Days between fertilizing'),
        ),
        migrations.AddField(
            model_name='dynamiccarecard',
            name='watering_frequency',
            field=models.IntegerField(default=7, help_text='Days between watering'),
        ),
    ]
