# Generated by Django 6.0.6 on 2026-06-28 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0014_dynamiccarecard_fertilizer_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotanistAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('urgent', 'Urgent')], default='standard', max_length=20)),
                ('symptoms', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='botanist_appointments/')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('distance', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], default='online', max_length=20)),
                ('preferred_botanist', models.CharField(blank=True, max_length=100)),
                ('assigned_botanist', models.CharField(default='Not Assigned', max_length=100)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('treating', 'Treating'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('distance_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('prescription_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='botanist_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PottingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pots', models.JSONField(default=list, help_text='List of selected pot/plant configurations')),
                ('pot_count', models.IntegerField(default=0)),
                ('soil_type', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potting_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
