# Generated by Django 6.0.6 on 2026-06-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0015_botanistappointment_pottingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pottingrequest',
            name='soil_type',
        ),
        migrations.AddField(
            model_name='pottingrequest',
            name='assigned_expert',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
        migrations.AddField(
            model_name='pottingrequest',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pottingrequest',
            name='package_type',
            field=models.CharField(choices=[('labor', 'Labor Only'), ('soil', 'Soil & Fertilizer')], default='labor', max_length=20),
        ),
        migrations.AddField(
            model_name='pottingrequest',
            name='pots_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pottingrequest',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pottingrequest',
            name='travel_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pottingrequest',
            name='pots',
            field=models.JSONField(default=dict, help_text='Breakdown of small/medium/large pot counts'),
        ),
    ]
